version: "3.9"
services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: masterkey
      DB_NAME: gestion_abako
      DB_PORT: 3306
      PORT: 3300
      JWT_SECRET: Masterkey

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: masterkey
      MYSQL_DATABASE: gestion_abako
      MYSQL_USER: root
      MYSQL_PASSWORD: masterkey
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
